#! /bin/bash

CHROOT=/var/lib/dgamelaunch

set -e
echo "Installing dgl config files..."

if [[ "$UID" != "0" ]; then
    echo -e "This script must be run as root."
    exit 1
fi

if [[ ! -f dgamelaunch.conf ]]; then
    echo -e "Can't find dgamelaunch.conf: must be in the current directory."
fi

do-copy-files() {
    local message=$1
    shift
    local target=$1
    shift
    echo "$message"
    if [[ ! -d "$target" ]]; then
        echo "Creating target directory: $target"
        mkdir -p "$target"
    fi
    cp $* "$target"
}

do-copy() {
    local message=$1
    shift
    local target=$1
    shift
    echo "$message"
    if [[ -L "$target" ]]; then
        echo "Target file ($target) for $@ is a symlink, cannot overwrite."
        exit 1
    fi
    cp $* $target
}

do-copy-files "Installing menu files" $CHROOT/data/menus data/menus/*.txt
do-copy "Installing dgamelaunch.conf" /etc ./dgamelaunch.conf
do-copy-files "Installing chroot scripts" $CHROOT/bin chroot/bin/*