#! /bin/bash

source "$DGL_CONF_HOME/dgl-manage.conf"

DGL_CONF_LOCK_DIR="$DGL_CONF_HOME/locks"

declare -a DGL_LOCKS
DGL_LOCKS=()

PROMPTS_DISABLED=

say() {
    echo "** $@ **"
}

say-do() {
    say "Exec: $@"
    "$@"
}

announce() {
    echo
    echo "---------------------------------------------------------------------"
    echo "$@"
    echo "$@" >>$ANNOUNCEMENTS_FILE
}

abort-saying() {
    echo -e "$@"
    echo -e "Aborting..."
    exit 1
}

# Call with any argument to disable prompts
disable-prompts() {
    if (( $# > 0 )); then
        PROMPTS_DISABLED=1
    fi
}

prompts-enabled() {
    # Prompts are enabled if not explicitly disabled, and if stdin is a tty.
    [[ -z "$PROMPTS_DISABLED" && -t 0 ]]
}

prompt() {
    if prompts-enabled; then
        echo "-- Press RETURN to $@ --"
        read
    else
        say "$@"
    fi
}

unlock-dgl-locks() {
    if (( "${#DGL_LOCKS[@]}" > 0 )); then
        rm -f ${DGL_LOCKS[@]}
    fi
}

unlock-on-error() {
    unlock-dgl-locks
    exit 1
}

trap-lock-hook-cleanup() {
    if [[ -z "$DGL_TRAP_LOCK_CLEANUP_HOOKED" ]]; then
        trap unlock-on-error INT TERM
        trap unlock-dgl-locks EXIT
        DGL_TRAP_LOCK_CLEANUP_HOOKED=1
    fi
}

lock-or-die() {
    local lock_name=$1
    mkdir -p "$DGL_CONF_LOCK_DIR"
    local lock_file="$DGL_CONF_LOCK_DIR/${lock_name}.lock"
    shift || true
    if ( set -o noclobber; echo "$$" > "$lock_file" ) 2>/dev/null; then
        DGL_LOCKS=(${DGL_LOCKS[@]} "$lock_file")
        trap-lock-hook-cleanup
    else
        echo "Could not lock $lock_file: $@"
        exit 1
    fi
}

dgl-today() {
    date +%y%m%d-%H%M
}

check-chroot-exists() {
    if [[ ! -d "$DGL_CHROOT" ]]; then
        cat >&2 <<ERROR
DGL chroot $DGL_CHROOT doesn't exist.

Please create it, or edit $DGL_CONF_HOME/dgl-manage.conf to
point at the real chroot.
ERROR
        exit 1
    fi
}
 
disable-prompts $*