[[games]]
id = "dcss-0.15"
name = "DCSS 0.15"
version = "0.15"
mode = "Dungeon Crawl"
morgue_url = "http://trilobyte/crawl/morgue/%n/"
crawl_binary = "/bin/crawl-stable-launcher.sh"
pre_options = [ "0.15",]
inprogress_path = "%%CHROOT_INPROGRESSDIR%%/crawl-15/"
rcfile_path = "%%CHROOT_RCFILESDIR%%/crawl-0.15/"
socket_path = "%%CHROOT_WEBDIR%%/sockets"
morgue_path = "%%CHROOT_MORGUEDIR%%/%n/"
macro_path = "%%CHROOT_RCFILESDIR%%/crawl-0.15/"
ttyrec_path = "%%CHROOT_TTYRECDIR%%/%n/"
score_path = "%%CHROOT_CRAWL_BASEDIR%%/crawl-0.15/saves/scores"
send_json_options = true

[[games]]
id = "spr-0.15"
name = "Sprint 0.15"
version = "0.15"
mode = "Dungeon Sprint"
morgue_url = "http://trilobyte/crawl/morgue/%n/"
crawl_binary = "/bin/crawl-stable-launcher.sh"
options = [ "-sprint",]
pre_options = [ "0.15",]
inprogress_path = "%%CHROOT_INPROGRESSDIR%%/crawl-15-sprint/"
rcfile_path = "%%CHROOT_RCFILESDIR%%/crawl-0.15/"
socket_path = "%%CHROOT_WEBDIR%%/sockets"
morgue_path = "%%CHROOT_MORGUEDIR%%/%n/"
macro_path = "%%CHROOT_RCFILESDIR%%/crawl-0.15/"
ttyrec_path = "%%CHROOT_TTYRECDIR%%/%n/"
score_path = "%%CHROOT_CRAWL_BASEDIR%%/crawl-0.15/saves/sprint-%m"
map_path = "%%CHROOT_CRAWL_BASEDIR%%/crawl-0.15/data/dat/des/sprint/sprint.toml"
send_json_options = true

[[games]]
id = "zd-0.15"
name = "Zot Defence 0.15"
version = "0.15"
mode = "Zot Defence"
morgue_url = "http://trilobyte/crawl/morgue/%n/"
crawl_binary = "/bin/crawl-stable-launcher.sh"
options = [ "-zotdef",]
pre_options = [ "0.15",]
inprogress_path = "%%CHROOT_INPROGRESSDIR%%/crawl-15-zotdef/"
rcfile_path = "%%CHROOT_RCFILESDIR%%/crawl-0.15/"
socket_path = "%%CHROOT_WEBDIR%%/sockets"
morgue_path = "%%CHROOT_MORGUEDIR%%/%n/"
macro_path = "%%CHROOT_RCFILESDIR%%/crawl-0.15/"
ttyrec_path = "%%CHROOT_TTYRECDIR%%/%n/"
score_path = "%%CHROOT_CRAWL_BASEDIR%%/crawl-0.15/saves/scores-zotdef"
send_json_options = true

[[games]]
id = "tut-0.15"
name = "Tutorial 0.15"
version = "0.15"
mode = "Tutorial"
crawl_binary = "/bin/crawl-stable-launcher.sh"
options = [ "-tutorial",]
pre_options = [ "0.15",]
inprogress_path = "%%CHROOT_INPROGRESSDIR%%/crawl-15-tut/"
rcfile_path = "%%CHROOT_RCFILESDIR%%/crawl-0.15/"
socket_path = "%%CHROOT_WEBDIR%%/sockets"
morgue_path = "%%CHROOT_MORGUEDIR%%/%n/"
macro_path = "%%CHROOT_RCFILESDIR%%/crawl-0.15/"
ttyrec_path = "%%CHROOT_TTYRECDIR%%/%n/"
send_json_options = true

[[games]]
id = "dcss-0.14"
name = "DCSS 0.14"
version = "0.14"
mode = "Dungeon Crawl"
morgue_url = "http://trilobyte/crawl/morgue/%n/"
crawl_binary = "/bin/crawl-stable-launcher.sh"
pre_options = [ "0.14",]
inprogress_path = "%%CHROOT_INPROGRESSDIR%%/crawl-14/"
rcfile_path = "%%CHROOT_RCFILESDIR%%/crawl-0.14/"
socket_path = "%%CHROOT_WEBDIR%%/sockets"
morgue_path = "%%CHROOT_MORGUEDIR%%/%n/"
macro_path = "%%CHROOT_RCFILESDIR%%/crawl-0.14/"
ttyrec_path = "%%CHROOT_TTYRECDIR%%/%n/"
score_path = "%%CHROOT_CRAWL_BASEDIR%%/crawl-0.14/saves/scores"
send_json_options = true

[[games]]
id = "spr-0.14"
name = "Sprint 0.14"
version = "0.14"
mode = "Dungeon Sprint"
morgue_url = "http://trilobyte/crawl/morgue/%n/"
crawl_binary = "/bin/crawl-stable-launcher.sh"
options = [ "-sprint",]
pre_options = [ "0.14",]
inprogress_path = "%%CHROOT_INPROGRESSDIR%%/crawl-14-sprint/"
rcfile_path = "%%CHROOT_RCFILESDIR%%/crawl-0.14/"
socket_path = "%%CHROOT_WEBDIR%%/sockets"
morgue_path = "%%CHROOT_MORGUEDIR%%/%n/"
macro_path = "%%CHROOT_RCFILESDIR%%/crawl-0.14/"
ttyrec_path = "%%CHROOT_TTYRECDIR%%/%n/"
score_path = "%%CHROOT_CRAWL_BASEDIR%%/crawl-0.14/saves/sprint-%m"
map_path = "%%CHROOT_CRAWL_BASEDIR%%/crawl-0.14/data/dat/des/sprint/sprint.toml"
send_json_options = true

[[games]]
id = "zd-0.14"
name = "Zot Defence 0.14"
version = "0.14"
mode = "Zot Defence"
morgue_url = "http://trilobyte/crawl/morgue/%n/"
crawl_binary = "/bin/crawl-stable-launcher.sh"
options = [ "-zotdef",]
pre_options = [ "0.14",]
inprogress_path = "%%CHROOT_INPROGRESSDIR%%/crawl-14-zotdef/"
rcfile_path = "%%CHROOT_RCFILESDIR%%/crawl-0.14/"
socket_path = "%%CHROOT_WEBDIR%%/sockets"
morgue_path = "%%CHROOT_MORGUEDIR%%/%n/"
macro_path = "%%CHROOT_RCFILESDIR%%/crawl-0.14/"
ttyrec_path = "%%CHROOT_TTYRECDIR%%/%n/"
score_path = "%%CHROOT_CRAWL_BASEDIR%%/crawl-0.14/saves/scores-zotdef"
send_json_options = true

[[games]]
id = "tut-0.14"
name = "Tutorial 0.14"
version = "0.14"
mode = "Tutorial"
crawl_binary = "/bin/crawl-stable-launcher.sh"
options = [ "-tutorial",]
pre_options = [ "0.14",]
inprogress_path = "%%CHROOT_INPROGRESSDIR%%/crawl-14-tut/"
rcfile_path = "%%CHROOT_RCFILESDIR%%/crawl-0.14/"
socket_path = "%%CHROOT_WEBDIR%%/sockets"
morgue_path = "%%CHROOT_MORGUEDIR%%/%n/"
macro_path = "%%CHROOT_RCFILESDIR%%/crawl-0.14/"
ttyrec_path = "%%CHROOT_TTYRECDIR%%/%n/"
send_json_options = true

[[games]]
id = "dcss-0.13"
name = "DCSS 0.13"
version = "0.13"
mode = "Dungeon Crawl"
morgue_url = "http://trilobyte/crawl/morgue/%n/"
crawl_binary = "/bin/crawl-stable-launcher.sh"
pre_options = [ "0.13",]
inprogress_path = "%%CHROOT_INPROGRESSDIR%%/crawl-13/"
rcfile_path = "%%CHROOT_RCFILESDIR%%/crawl-0.13/"
socket_path = "%%CHROOT_WEBDIR%%/sockets"
morgue_path = "%%CHROOT_MORGUEDIR%%/%n/"
macro_path = "%%CHROOT_RCFILESDIR%%/crawl-0.13/"
ttyrec_path = "%%CHROOT_TTYRECDIR%%/%n/"
score_path = "%%CHROOT_CRAWL_BASEDIR%%/crawl-0.13/saves/scores"
send_json_options = true

[[games]]
id = "spr-0.13"
name = "Sprint 0.13"
version = "0.13"
mode = "Dungeon Sprint"
morgue_url = "http://trilobyte/crawl/morgue/%n/"
crawl_binary = "/bin/crawl-stable-launcher.sh"
options = [ "-sprint",]
pre_options = [ "0.13",]
inprogress_path = "%%CHROOT_INPROGRESSDIR%%/crawl-13-sprint/"
rcfile_path = "%%CHROOT_RCFILESDIR%%/crawl-0.13/"
socket_path = "%%CHROOT_WEBDIR%%/sockets"
morgue_path = "%%CHROOT_MORGUEDIR%%/%n/"
macro_path = "%%CHROOT_RCFILESDIR%%/crawl-0.13/"
ttyrec_path = "%%CHROOT_TTYRECDIR%%/%n/"
score_path = "%%CHROOT_CRAWL_BASEDIR%%/crawl-0.13/saves/sprint-%m"
map_path = "%%CHROOT_CRAWL_BASEDIR%%/crawl-0.13/data/dat/des/sprint/sprint.toml"
send_json_options = true

[[games]]
id = "zd-0.13"
name = "Zot Defence 0.13"
version = "0.13"
mode = "Zot Defence"
morgue_url = "http://trilobyte/crawl/morgue/%n/"
crawl_binary = "/bin/crawl-stable-launcher.sh"
options = [ "-zotdef",]
pre_options = [ "0.13",]
inprogress_path = "%%CHROOT_INPROGRESSDIR%%/crawl-13-zotdef/"
rcfile_path = "%%CHROOT_RCFILESDIR%%/crawl-0.13/"
socket_path = "%%CHROOT_WEBDIR%%/sockets"
morgue_path = "%%CHROOT_MORGUEDIR%%/%n/"
macro_path = "%%CHROOT_RCFILESDIR%%/crawl-0.13/"
ttyrec_path = "%%CHROOT_TTYRECDIR%%/%n/"
score_path = "%%CHROOT_CRAWL_BASEDIR%%/crawl-0.13/saves/scores-zotdef"
send_json_options = true

[[games]]
id = "tut-0.13"
name = "Tutorial 0.13"
version = "0.13"
mode = "Tutorial"
crawl_binary = "/bin/crawl-stable-launcher.sh"
options = [ "-tutorial",]
pre_options = [ "0.13",]
inprogress_path = "%%CHROOT_INPROGRESSDIR%%/crawl-13-tut/"
rcfile_path = "%%CHROOT_RCFILESDIR%%/crawl-0.13/"
socket_path = "%%CHROOT_WEBDIR%%/sockets"
morgue_path = "%%CHROOT_MORGUEDIR%%/%n/"
macro_path = "%%CHROOT_RCFILESDIR%%/crawl-0.13/"
ttyrec_path = "%%CHROOT_TTYRECDIR%%/%n/"
send_json_options = true

[[games]]
id = "dcss-0.12"
name = "DCSS 0.12"
version = "0.12"
mode = "Dungeon Crawl"
morgue_url = "http://trilobyte/crawl/morgue/%n/"
crawl_binary = "/bin/crawl-stable-launcher.sh"
pre_options = [ "0.12",]
inprogress_path = "%%CHROOT_INPROGRESSDIR%%/crawl-12/"
rcfile_path = "%%CHROOT_RCFILESDIR%%/crawl-0.12/"
socket_path = "%%CHROOT_WEBDIR%%/sockets"
morgue_path = "%%CHROOT_MORGUEDIR%%/%n/"
macro_path = "%%CHROOT_RCFILESDIR%%/crawl-0.12/"
ttyrec_path = "%%CHROOT_TTYRECDIR%%/%n/"
score_path = "%%CHROOT_CRAWL_BASEDIR%%/crawl-0.12/saves/scores"
send_json_options = true

[[games]]
id = "spr-0.12"
name = "Sprint 0.12"
version = "0.12"
mode = "Dungeon Sprint"
morgue_url = "http://trilobyte/crawl/morgue/%n/"
crawl_binary = "/bin/crawl-stable-launcher.sh"
options = [ "-sprint",]
pre_options = [ "0.12",]
inprogress_path = "%%CHROOT_INPROGRESSDIR%%/crawl-12-sprint/"
rcfile_path = "%%CHROOT_RCFILESDIR%%/crawl-0.12/"
socket_path = "%%CHROOT_WEBDIR%%/sockets"
morgue_path = "%%CHROOT_MORGUEDIR%%/%n/"
macro_path = "%%CHROOT_RCFILESDIR%%/crawl-0.12/"
ttyrec_path = "%%CHROOT_TTYRECDIR%%/%n/"
score_path = "%%CHROOT_CRAWL_BASEDIR%%/crawl-0.12/saves/scores-sprint"
map_path = "%%CHROOT_CRAWL_BASEDIR%%/crawl-0.12/data/dat/des/sprint/sprint.toml"
send_json_options = true

[[games]]
id = "zd-0.12"
name = "Zot Defence 0.12"
version = "0.12"
mode = "Zot Defence"
morgue_url = "http://trilobyte/crawl/morgue/%n/"
crawl_binary = "/bin/crawl-stable-launcher.sh"
options = [ "-zotdef",]
pre_options = [ "0.12",]
inprogress_path = "%%CHROOT_INPROGRESSDIR%%/crawl-12-zotdef/"
rcfile_path = "%%CHROOT_RCFILESDIR%%/crawl-0.12/"
socket_path = "%%CHROOT_WEBDIR%%/sockets"
morgue_path = "%%CHROOT_MORGUEDIR%%/%n/"
macro_path = "%%CHROOT_RCFILESDIR%%/crawl-0.12/"
ttyrec_path = "%%CHROOT_TTYRECDIR%%/%n/"
score_path = "%%CHROOT_CRAWL_BASEDIR%%/crawl-0.12/saves/scores-zotdef"
send_json_options = true

[[games]]
id = "tut-0.12"
name = "Tutorial 0.12"
version = "0.12"
mode = "Tutorial"
crawl_binary = "/bin/crawl-stable-launcher.sh"
options = [ "-tutorial",]
pre_options = [ "0.12",]
inprogress_path = "%%CHROOT_INPROGRESSDIR%%/crawl-12-tut/"
rcfile_path = "%%CHROOT_RCFILESDIR%%/crawl-0.12/"
socket_path = "%%CHROOT_WEBDIR%%/sockets"
morgue_path = "%%CHROOT_MORGUEDIR%%/%n/"
macro_path = "%%CHROOT_RCFILESDIR%%/crawl-0.12/"
ttyrec_path = "%%CHROOT_TTYRECDIR%%/%n/"
send_json_options = true

[[games]]
id = "dcss-0.11"
name = "DCSS 0.11"
version = "0.11"
mode = "Dungeon Crawl"
morgue_url = "http://trilobyte/crawl/morgue/%n/"
crawl_binary = "/bin/crawl-stable-launcher.sh"
pre_options = [ "0.11",]
inprogress_path = "%%CHROOT_INPROGRESSDIR%%/crawl-11/"
rcfile_path = "%%CHROOT_RCFILESDIR%%/crawl-0.11/"
socket_path = "%%CHROOT_WEBDIR%%/sockets"
morgue_path = "%%CHROOT_MORGUEDIR%%/%n/"
macro_path = "%%CHROOT_RCFILESDIR%%/crawl-0.11/"
ttyrec_path = "%%CHROOT_TTYRECDIR%%/%n/"
score_path = "%%CHROOT_CRAWL_BASEDIR%%/crawl-0.11/saves/scores"
send_json_options = true

[[games]]
id = "spr-0.11"
name = "Sprint 0.11"
version = "0.11"
mode = "Dungeon Sprint"
morgue_url = "http://trilobyte/crawl/morgue/%n/"
crawl_binary = "/bin/crawl-stable-launcher.sh"
options = [ "-sprint",]
pre_options = [ "0.11",]
inprogress_path = "%%CHROOT_INPROGRESSDIR%%/crawl-11-sprint/"
rcfile_path = "%%CHROOT_RCFILESDIR%%/crawl-0.11/"
socket_path = "%%CHROOT_WEBDIR%%/sockets"
morgue_path = "%%CHROOT_MORGUEDIR%%/%n/"
macro_path = "%%CHROOT_RCFILESDIR%%/crawl-0.11/"
ttyrec_path = "%%CHROOT_TTYRECDIR%%/%n/"
score_path = "%%CHROOT_CRAWL_BASEDIR%%/crawl-0.11/saves/scores-sprint"
map_path = "%%CHROOT_CRAWL_BASEDIR%%/crawl-0.11/data/dat/des/sprint/sprint.toml"
send_json_options = true

[[games]]
id = "zd-0.11"
name = "Zot Defence 0.11"
version = "0.11"
mode = "Zot Defence"
morgue_url = "http://trilobyte/crawl/morgue/%n/"
crawl_binary = "/bin/crawl-stable-launcher.sh"
options = [ "-zotdef",]
pre_options = [ "0.11",]
inprogress_path = "%%CHROOT_INPROGRESSDIR%%/crawl-11-zotdef/"
rcfile_path = "%%CHROOT_RCFILESDIR%%/crawl-0.11/"
socket_path = "%%CHROOT_WEBDIR%%/sockets"
morgue_path = "%%CHROOT_MORGUEDIR%%/%n/"
macro_path = "%%CHROOT_RCFILESDIR%%/crawl-0.11/"
ttyrec_path = "%%CHROOT_TTYRECDIR%%/%n/"
score_path = "%%CHROOT_CRAWL_BASEDIR%%/crawl-0.11/saves/scores-zotdef"
send_json_options = true

[[games]]
id = "tut-0.11"
name = "Tutorial 0.11"
version = "0.11"
mode = "Tutorial"
crawl_binary = "/bin/crawl-stable-launcher.sh"
options = [ "-tutorial",]
pre_options = [ "0.11",]
inprogress_path = "%%CHROOT_INPROGRESSDIR%%/crawl-11-tut/"
rcfile_path = "%%CHROOT_RCFILESDIR%%/crawl-0.11/"
socket_path = "%%CHROOT_WEBDIR%%/sockets"
morgue_path = "%%CHROOT_MORGUEDIR%%/%n/"
macro_path = "%%CHROOT_RCFILESDIR%%/crawl-0.11/"
ttyrec_path = "%%CHROOT_TTYRECDIR%%/%n/"
send_json_options = true

[[games]]
id = "dcss-0.10"
name = "DCSS 0.10"
version = "0.10"
mode = "Dungeon Crawl"
morgue_url = "http://trilobyte/crawl/morgue/%n/"
crawl_binary = "/bin/crawl-stable-launcher.sh"
pre_options = [ "0.10",]
inprogress_path = "%%CHROOT_INPROGRESSDIR%%/crawl-10/"
rcfile_path = "%%CHROOT_RCFILESDIR%%/crawl-0.10/"
socket_path = "%%CHROOT_WEBDIR%%/sockets"
morgue_path = "%%CHROOT_MORGUEDIR%%/%n/"
macro_path = "%%CHROOT_RCFILESDIR%%/crawl-0.10/"
ttyrec_path = "%%CHROOT_TTYRECDIR%%/%n/"
score_path = "%%CHROOT_CRAWL_BASEDIR%%/crawl-0.10/saves/scores"
send_json_options = true

[[games]]
id = "spr-0.10"
name = "Sprint 0.10"
version = "0.10"
mode = "Dungeon Sprint"
morgue_url = "http://trilobyte/crawl/morgue/%n/"
crawl_binary = "/bin/crawl-stable-launcher.sh"
options = [ "-sprint",]
pre_options = [ "0.10",]
inprogress_path = "%%CHROOT_INPROGRESSDIR%%/crawl-10-sprint/"
rcfile_path = "%%CHROOT_RCFILESDIR%%/crawl-0.10/"
socket_path = "%%CHROOT_WEBDIR%%/sockets"
morgue_path = "%%CHROOT_MORGUEDIR%%/%n/"
macro_path = "%%CHROOT_RCFILESDIR%%/crawl-0.10/"
ttyrec_path = "%%CHROOT_TTYRECDIR%%/%n/"
score_path = "%%CHROOT_CRAWL_BASEDIR%%/crawl-0.10/saves/scores-sprint"
map_path = "%%CHROOT_CRAWL_BASEDIR%%/crawl-0.10/data/dat/des/sprint/sprint.toml"
send_json_options = true

[[games]]
id = "zd-0.10"
name = "Zot Defence 0.10"
version = "0.10"
mode = "Zot Defence"
morgue_url = "http://trilobyte/crawl/morgue/%n/"
crawl_binary = "/bin/crawl-stable-launcher.sh"
options = [ "-zotdef",]
pre_options = [ "0.10",]
inprogress_path = "%%CHROOT_INPROGRESSDIR%%/crawl-10-zotdef/"
rcfile_path = "%%CHROOT_RCFILESDIR%%/crawl-0.10/"
socket_path = "%%CHROOT_WEBDIR%%/sockets"
morgue_path = "%%CHROOT_MORGUEDIR%%/%n/"
macro_path = "%%CHROOT_RCFILESDIR%%/crawl-0.10/"
ttyrec_path = "%%CHROOT_TTYRECDIR%%/%n/"
score_path = "%%CHROOT_CRAWL_BASEDIR%%/crawl-0.10/saves/scores-zotdef"
send_json_options = true

[[games]]
id = "tut-0.10"
name = "Tutorial 0.10"
version = "0.10"
mode = "Tutorial"
crawl_binary = "/bin/crawl-stable-launcher.sh"
options = [ "-tutorial",]
pre_options = [ "0.10",]
inprogress_path = "%%CHROOT_INPROGRESSDIR%%/crawl-10-tut/"
rcfile_path = "%%CHROOT_RCFILESDIR%%/crawl-0.10/"
socket_path = "%%CHROOT_WEBDIR%%/sockets"
morgue_path = "%%CHROOT_MORGUEDIR%%/%n/"
macro_path = "%%CHROOT_RCFILESDIR%%/crawl-0.10/"
ttyrec_path = "%%CHROOT_TTYRECDIR%%/%n/"
send_json_options = true
