[[games]]
id = "dcss-smithgod_rebased"
name = "Smith God (Updated)"
mode = "Dungeon Crawl"
morgue_url = "http://dobrazupa.org/morgue/%n/"
crawl_binary = "/bin/crawl-stable-launcher.sh"
pre_options = [ "iashol",]
inprogress_path = "%%CHROOT_INPROGRESSDIR%%/crawl-smithgod_rebased"
rcfile_path = "%%CHROOT_RCFILESDIR%%/crawl-git/"
socket_path = "%%CHROOT_WEBDIR%%/sockets"
morgue_path = "%%CHROOT_MORGUEDIR%%/%n/"
macro_path = "%%CHROOT_RCFILESDIR%%/crawl-git/"
ttyrec_path = "%%CHROOT_TTYRECDIR%%/%n/"
score_path = "%%CHROOT_CRAWL_BASEDIR%%/crawl-smithgod_rebased/saves/scores"
send_json_options = true
